# Generated by Django 4.0.6 on 2023-03-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eproductapi', '0002_products_available_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='offer',
            new_name='offer_discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
    ]
